ministryofjustice/hmpps-registers

README.md
integration_tests/index.d.ts
integration_tests/integration/court-register.spec.ts
integration_tests/mockApis/courtRegister.ts
integration_tests/pages/court-register/allCourtsPaged.ts
integration_tests/plugins/index.ts
server/routes/courtRegister/allCourtsPagedView.test.ts
server/routes/courtRegister/allCourtsPagedView.ts
server/routes/courtRegister/courtMapper.test.ts
server/routes/courtRegister/courtMapper.ts
server/routes/courtRegister/courtRegisterController.test.ts
server/routes/courtRegister/courtRegisterController.ts
server/routes/courtRegister/courtRegisterRouter.ts
server/services/courtRegisterService.test.ts
server/services/courtRegisterService.ts
server/views/pages/court-register/allCourtsPaged.njk

This currently lives at the hidden URL /court-register/paged - when it is fully functional I will switch it to the main list.

DT-1768 paged court list

---

integration_tests/integration/court-register.spec.ts
server/routes/courtRegister/allCourtsPagedView.test.ts
server/routes/courtRegister/allCourtsView.test.ts
server/routes/courtRegister/courtMapper.ts
server/routes/courtRegister/courtRegisterController.test.ts
server/routes/courtRegister/courtRegisterController.ts
server/routes/testutils/mockData.ts
server/services/courtRegisterService.test.ts
server/services/courtRegisterService.ts

Fixes as suggested from previous review
* Use court type description
* Sort by court name
* Show 40 courts per page

DT-1846 fixes

---

integration_tests/integration/court-register.spec.ts
integration_tests/pages/court-register/amendCourtDetails.ts
integration_tests/pages/court-register/courtDetails.ts
server/@types/forms/index.d.ts
server/routes/courtRegister/amendCourtDetailsView.test.ts
server/routes/courtRegister/amendCourtDetailsView.ts
server/routes/courtRegister/courtRegisterController.test.ts
server/routes/courtRegister/courtRegisterController.ts
server/routes/courtRegister/courtRegisterRouter.ts
server/views/pages/court-register/amendCourtDetails.njk
server/views/pages/court-register/courtDetails.njk

This PR allows the user to navigate to the amend court details page.
[Next step will be handling the submit from the amend]

DT-1769 Can navigate to the amend page

---

server/views/pages/court-register/allCourtsPaged.njk

There are no changes here other than indenting - required to prevent the next PR from being unreadable.

DT-1846 Apply correct formatting to page

---

server/@types/express/index.d.ts
server/routes/courtRegister/amendCourtDetailsValidator.test.ts
server/routes/courtRegister/amendCourtDetailsValidator.ts
server/routes/courtRegister/amendCourtDetailsView.test.ts
server/routes/courtRegister/amendCourtDetailsView.ts
server/routes/courtRegister/courtRegisterController.test.ts
server/routes/courtRegister/courtRegisterController.ts
server/routes/courtRegister/courtRegisterRouter.ts
server/services/courtRegisterService.test.ts
server/services/courtRegisterService.ts
server/views/pages/court-register/addNewCourtDetails.njk
server/views/pages/court-register/amendCourtDetails.njk
server/views/pages/court-register/courtDetails.njk

Still todo
1) Cypress tests
2) Confirmation message on court details page
3) Also like to address mixing of courtId and Id in frontend

DT-1769 Call validate and call service to update

---

assets/js/court-type-filter-toggle-button.js
server/app.ts
server/routes/courtRegister/allCourtsPagedView.ts
server/routes/courtRegister/courtMapper.ts
server/utils/nunjucksSetup.test.ts
server/utils/nunjucksSetup.ts
server/views/pages/court-register/allCourtsPaged.njk
server/views/partials/layout.njk

Show the filter in the UI - it doesn't do anything yet and doesn't show all court types, coming in next PR.

DT-1846 display filter

---

.circleci/config.yml
assets/js/court-type-filter-toggle-button.js
integration_tests/integration/court-register-list.spec.ts
integration_tests/pages/court-register/allCourtsPaged.ts
server/routes/courtRegister/allCourtsPagedView.test.ts
server/routes/courtRegister/allCourtsPagedView.ts
server/routes/courtRegister/courtMapper.test.ts
server/routes/courtRegister/courtMapper.ts
server/routes/courtRegister/courtRegisterController.test.ts
server/routes/courtRegister/courtRegisterController.ts
server/services/courtRegisterService.test.ts
server/services/courtRegisterService.ts
server/utils/nunjucksSetup.test.ts
server/utils/nunjucksSetup.ts
server/views/pages/court-register/allCourtsPaged.njk

This PR applies the filter and reloads the page.  However it is not quite fully functional - still need to load the court types from the API, and also the "remove selected filter" buttons are not yet implemented.

DT-1846 apply filter

---

server/routes/courtRegister/amendCourtBuildingValidator.test.ts
server/routes/courtRegister/amendCourtBuildingValidator.ts
server/routes/courtRegister/courtRegisterController.ts
server/services/courtRegisterService.test.ts
server/services/courtRegisterService.ts
server/views/pages/court-register/amendCourtBuilding.njk
server/views/pages/court-register/courtDetails.njk

* subside added to amend building
* Validation added to check it doesn't match a court
* Validation added to check it doesn't match a court building

DT-1773 Add subcode and lookup validation

---

package-lock.json

DT-1773 Dependency updates

---

server/@types/express/index.d.ts
server/routes/courtRegister/addNewCourtBuildingView.test.ts
server/routes/courtRegister/addNewCourtBuildingView.ts
server/routes/courtRegister/addNewCourtContactDetailsView.test.ts
server/routes/courtRegister/addNewCourtContactDetailsView.ts
server/routes/courtRegister/addNewCourtDetailsView.test.ts
server/routes/courtRegister/addNewCourtDetailsView.ts
server/routes/courtRegister/addNewCourtSummaryView.test.ts
server/routes/courtRegister/addNewCourtSummaryView.ts
server/routes/courtRegister/amendCourtBuildingView.ts
server/routes/courtRegister/courtDetailsView.test.ts
server/routes/courtRegister/courtDetailsView.ts
server/routes/courtRegister/courtMapper.test.ts
server/routes/courtRegister/courtMapper.ts
server/routes/courtRegister/courtRegisterController.test.ts
server/routes/courtRegister/courtRegisterController.ts
server/views/pages/court-register/addNewCourtBuilding.njk
server/views/pages/court-register/addNewCourtContactDetails.njk
server/views/pages/court-register/addNewCourtDetails.njk
server/views/pages/court-register/addNewCourtFinished.njk
server/views/pages/court-register/addNewCourtSummary.njk
server/views/pages/court-register/courtDetails.njk

Apply the current filter to all back and cancel links

DT-1846 fix back links

---

assets/js/mojFrontendInit.js
integration_tests/integration/court-register-amend.spec.ts
integration_tests/mockApis/courtRegister.ts
integration_tests/pages/court-register/amendCourtBuildingContacts.ts
integration_tests/pages/court-register/courtDetails.ts
server/@types/express/index.d.ts
server/@types/forms/index.d.ts
server/routes/courtRegister/amendCourtBuildingContactsView.ts
server/routes/courtRegister/courtRegisterController.test.ts
server/routes/courtRegister/courtRegisterController.ts
server/routes/courtRegister/courtRegisterRouter.ts
server/utils/nunjucksSetup.ts
server/views/pages/court-register/amendCourtBuildingContacts.njk
server/views/partials/layout.njk

* Can navigate to the amend contacts page
* TODO - validate form
* TODO - save and update contacts

Dt 1772 amend contact

---

server/data/restClient.ts
server/services/courtRegisterService.test.ts
server/services/courtRegisterService.ts

Solves issue where API tries to save blank as a sub-code causing lookup issue

DT-1773 Ensure null is sent for blank court fields

---

server/@types/courtRegister/index.d.ts
server/@types/forms/index.d.ts
server/routes/courtRegister/amendCourtBuidingContactsValidator.test.ts
server/routes/courtRegister/amendCourtBuildingContactsValidator.ts
server/routes/courtRegister/courtRegisterController.test.ts
server/routes/courtRegister/courtRegisterController.ts
server/services/courtRegisterService.ts

TODO - actually do the updates

DT-1772 Controller now calls service

---

integration_tests/integration/court-register-amend.spec.ts
server/routes/courtRegister/courtRegisterController.test.ts
server/routes/courtRegister/courtRegisterController.ts
server/utils/trim.test.ts
server/utils/trim.ts

Tried express-validator but couldn't get to work with nested array form syntax

Dt 1976 remove trailing space in forms

---

integration_tests/integration/court-register-list.spec.ts
integration_tests/pages/court-register/allCourtsPaged.ts
server/routes/courtRegister/courtMapper.ts
server/routes/courtRegister/courtRegisterController.test.ts
server/routes/courtRegister/courtRegisterController.ts
server/utils/nunjucksSetup.test.ts
server/utils/nunjucksSetup.ts
server/views/pages/court-register/allCourts.njk

Adds text search to the filters, and also some tidying up around removing empty filters from query parameters.

DT-1954 text search

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

https://dsdmoj.atlassian.net/browse/HAAR-30

HAAR-30: configure PRISON_REGISTER_API_URL

---

integration_tests/integration/prison-register-details.spec.ts
integration_tests/integration/prison-register-list.spec.ts
integration_tests/pages/prison-register/allPrisons.ts
server/@types/prisonRegisterImport/index.d.ts
server/routes/courtRegister/courtRegisterController.ts
server/routes/prisonRegister/prisonDetailsView.test.ts
server/routes/prisonRegister/prisonMapper.test.ts
server/routes/prisonRegister/prisonMapper.ts
server/routes/prisonRegister/prisonRegisterController.test.ts
server/routes/prisonRegister/prisonRegisterController.ts
server/routes/testutils/mockPrisonData.ts
server/utils/nunjucksSetup.test.ts
server/utils/nunjucksSetup.ts
server/views/pages/prison-register/allPrisons.njk
server/views/pages/prison-register/prisonDetails.njk

https://dsdmoj.atlassian.net/browse/HAAR-161

HAAR-161: display and filter by gender

---

assets/sass/components/_govuk-overrides.scss

HAAR-407: Remove scrolls to the right

---

Dockerfile

Replaces https://github.com/ministryofjustice/hmpps-registers/pull/265

Update base image for Dockerfile to be inline with template

---

package-lock.json
package.json

[MAP-1586](https://dsdmoj.atlassian.net/browse/MAP-1586)
[MAP-1586]: https://dsdmoj.atlassian.net/browse/MAP-1586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-1586 dependency update

---

package-lock.json

Addresses: https://github.com/advisories/GHSA-75v8-2h7p-7m2m

dependency update
